import datetime

#SCANNER FILTER
MIN_PRICE = 5
MIN_DAILY_VOLUME = 500000
NASDAQ_TICKER_COUNT = 3500

#SCORING SYSTEM
MOVING_AVG_POINTS = 30
RSI_POINTS = 25
VOL_TRENDS_POINTS = 25
WEEK_POSITION_POINTS = 20

#RECOMENDATION TRESHOLDS
BUY_THRESHOLD = 75
WATCH_THRESHOLD = 50
HOLD_THRESHOLD = 25


MARKET_HOURS_START = datetime.time(9,30)
MARKET_HOURS_END =  datetime.time(16,0)